### PR TITLE
fix bug edit cohort

### PR DESCRIPTION
**Pull request by lubnaabd**
relates #70

### CODE REVIEW

**Review by NouraldinS — APPROVED** [review]

**Comment by NouraldinS** [comment]
Good job @lubnaabd, Paying attention to the details is good...

**Comment by ali-7** [comment]
> Good job @lubnaabd, Paying attention to the details is good...

@NoureldeanSaed  in process for checking all the website, maybe there will be commits after ur approvel

**Comment by NouraldinS** [comment]
@ali-7 I want to see 1000 branches... Do not commit after approval...

**Comment by ali-7** [comment]
> @ali-7 I want to see 1000 branches... Do not commit after approval...

@NoureldeanSaed :-1:  :smiley:

**Review by ali-7 — APPROVED** [review]

**Comment by ali-7** [comment]
@NoureldeanSaed  ok just for the :heart: :smiley:

**Pull request merged**
